spring:
  multiple:
    datasource:
      # 数据源-1
      base:
        url: jdbc:mysql://127.0.0.1:3306/base?useSSL=false&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useUnicode=true&autoReconnect=true&failOverReadOnly=false&useAffectedRows=true
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        # hikari连接池配置 对应 HikariConfig 配置属性类
        hikari:
          poolName: HikariCP-base
          #最小空闲连接数
          minimumIdle: 20
          # 空闲连接存活最大时间，默认10分钟
          idleTimeout: 600000
          # 连接池最大连接数，默认是10
          maximumPoolSize: 100
          # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
          autoCommit: true
          # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
          maxLifetime: 1800000
          # 数据库连接超时时间,默认30秒
          connectionTimeout: 30000
          # 连接测试query
          connectionTestQuery: SELECT 1
        mybatis:
          typeAliasesPackage: io.github.zhoujunlin94.kaido.repository.db.entity.base
          mapperLocation: classpath:mybatis/base/*.xml
          basePackages: io.github.zhoujunlin94.kaido.repository.db.mapper.base
          interceptors:
            - clazz: com.github.pagehelper.PageInterceptor
              properties:
                helperDialect: mysql
                reasonable: true
                supportMethodsArguments: true
            - clazz: io.github.zhoujunlin94.meet.tk_mybatis.interceptor.PrintSQLInterceptor
              properties:
                enable: true

  redis:
    host: localhost
    port: 16379
    password: meetredis
    database: 0
    lettuce:
      pool:
        # 最大活跃链接数 默认8（使用负值表示没有限制）
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  token-prefix: Bearer
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 1800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
